package quizapp;
import java.awt.*;
import javax.swing.*;

public class geo extends javax.swing.JFrame {

String[] question = {
"Q1.  How many continents are on the Earth?",
"Q2.  What country is the largest in the world?",
"Q3.  Which is the largest lake in the world?",
"Q4.  Which is the longest river in the world?",
"Q5.  What is the tallest building in the world?",
"Q6.  What is the tallest mountain in the world?",
"Q7.  The country which has the largest population in the world",
"Q8.  What is deepest place on the world?",
"Q9.  How many countries are in the world?",
"Q10.  The tallest waterfall on the world?",
"Q11.  The safest country on the Earth is?",
"Q12.  The biggest colonial empire is?",
"Q13.  What country has the largest economy?",
"Q14.  Taiwan is located in ........?",
"Q15.  Which river flows through Paris?",
"Q16.  The mountain range in Russia seperates Europe and Asia",
"Q17.  Which country's national colour is Orange?",
"Q18.  What is the largest US state by area?",
"Q19.  Which city is the Taj Mahal located in ......?",
"Q20.  What is the capital of Australia?",
"Q21.  Which ocean has the largest surface area?",
"Q22.  This country's national languages:English,Malay,Mandarin,Tamil",
"Q23.  Which of these cities is closest to the equator?",
"Q24.  Which country has the smallest population in the world?",
"Q25.  Which desert is in the India?"


};

//second item is the correct answer
String[][] options = {
/*1*/{"06","07","05","08"},
/*2*/{"Canada","Russia","China","USA"},
/*3*/{"Victoria","Caspian Sea","Huron","Superior"},
/*4*/{"Amazon","Nile","Brahmaputra","Yangtze"},
/*5*/{"Merdeka 118","Burj Khalifa","Lakhta Center","Shanghai Tower"},
/*6*/{"Kilimajaro","Mount Everest","Carpathian","Manaslu"},
/*7*/{"India","China","USA","Indonesia"},
/*8*/{"Dead Sea","The Mariana Trench","Gulf of Mexico","Bermuda Triangle"},
/*9*/{"192 countries","195 countries","172 countries","96 countries"},
/*10*/{"Victoria Falls","Angel Falls","Niagara Falls","Iguazu Falls"},
/*11*/{"Denmark","Iceland","Ireland","New Zealand"},
/*12*/{"Roman Empire","British Empire","Russian Empire","Mongol Empire"},
/*13*/{"Japan","United States","China","Germany"},
/*14*/{"Africa","Asia","Europe","Australia"},
/*15*/{"Amazon River","Seine River","Yellow River","Mississippi River"},
/*16*/{"Pyranees","Urals","Himalayas","Andes"},
/*17*/{"Indonesia","Netherlands","India","Singapore"},
/*18*/{"Alabama","Alaska","Arizona","Califonia"},
/*19*/{"Jaipur","Agra","Mumbai","Patna"},
/*20*/{"Hobart","Canberra","Wellington","Port Moresby"},
/*21*/{"Arctic Ocean","Pacific Ocean","Indian Ocean","Atlantic Ocean"},
/*22*/{"Indonesia","Singapore","India","Thailand"},
/*23*/{"Cairo","Nairobi","Rio De Janeiro","Jakarta"},
/*24*/{"San Marino","Vatican city","Monaco","Tuvalu"},
/*25*/{"Kalahari","Thar","Death Valley","Gobi"}

};


    int index = 0, correct = 0;
    ButtonGroup bg = new ButtonGroup();

    public geo() {
        initComponents();
        
        ImageIcon imagebg = new ImageIcon(new ImageIcon("p2.png").getImage().getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(), Image.SCALE_DEFAULT));
         jLabel2.setIcon(imagebg);
        
        bg.add(btn1);
        bg.add(btn2);
        bg.add(btn3);
        bg.add(btn4);
        
        nextActionPerformed(null);
                
       //setSize(570, 480);

    }
    
    public void getSelectedOption(JRadioButton bbtn){
        //to get selected value from the radio button
        //increament the index
        //display radio buttons
        //check if the user selected the correct ans
        
        System.out.println(bbtn.getText());
        System.out.println(options[index][1]);
                
        if(bbtn.getText().equals(options[index][1]))
        {
            correct++;
        }
        
        index++;
        enableradiobtns(false);
    }
    
    //enable/ disable radiobuttons
    public void enableradiobtns(boolean yesno){
        btn1.setEnabled(yesno);
        btn2.setEnabled(yesno);
        btn3.setEnabled(yesno);
        btn4.setEnabled(yesno);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn1 = new javax.swing.JRadioButton();
        btn2 = new javax.swing.JRadioButton();
        btn3 = new javax.swing.JRadioButton();
        btn4 = new javax.swing.JRadioButton();
        jButton6 = new javax.swing.JButton();
        next = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ques = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quizz Time - Geography");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(120, 59, 241));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quizz Time - Geography");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 70));

        btn1.setBackground(new java.awt.Color(204, 204, 204));
        btn1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn1.setText("btn1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 330, 30));

        btn2.setBackground(new java.awt.Color(204, 204, 204));
        btn2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn2.setText("btn2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 330, 30));

        btn3.setBackground(new java.awt.Color(204, 204, 204));
        btn3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn3.setText("btn3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 330, 30));

        btn4.setBackground(new java.awt.Color(204, 204, 204));
        btn4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn4.setText("btn4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 330, 30));

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("BACK");
        jButton6.setToolTipText("Click Here To Go To Quiz Time Dashboard");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 110, 34));

        next.setBackground(new java.awt.Color(51, 51, 51));
        next.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("NEXT");
        next.setToolTipText("Choose An Answer And Click Here To Go To Next Quiz");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 420, 110, 34));

        jLabel2.setText("jLabel1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 190, 180));

        ques.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ques.setText("ques");
        jPanel1.add(ques, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 550, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        //increament to go to next question
        getSelectedOption(btn1);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        getSelectedOption(btn2);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        getSelectedOption(btn3);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        getSelectedOption(btn4);
    }//GEN-LAST:event_btn4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        setVisible(false);
        f2 back = new f2();
        back.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

        if(next.getText().equals("RESTART"))
        {
            //restart the quiz
            next.setText("NEXT");
            jPanel1.setBackground(Color.WHITE);
            index = 0;
            correct = 0;
        }

        if(index == question.length)
        {
            //display the user score
            //ques.setText("Your Score: " + correct + " / " + question.length);

            if(correct >= 15)
            {
                JOptionPane optpanel = new JOptionPane();
                
                optpanel.setBackground(Color.GREEN);
                optpanel.showMessageDialog(null,"Congratulations!  Your Score is : " + correct + " / " + question.length,
                "Quiz Finished", optpanel.PLAIN_MESSAGE);
                
            }
            else{
                JOptionPane optpanel2 = new JOptionPane();
                optpanel2.setBackground(Color.RED);
                
                optpanel2.showMessageDialog(null,"Sorry!  Your Score is : " + correct + " / " + question.length,
                "Quiz Finished", optpanel2.PLAIN_MESSAGE);
                
                
                ques.setText("");
                btn1.setText("");
                btn2.setText("");
                btn3.setText("");
                btn4.setText("");
            }

            next.setText("RESTART");
        }

        else
        {
            //enable radio btns
            enableradiobtns(true);

            //display next question
            ques.setText(question[index]);

            btn1.setText(options[index][0]);
            btn2.setText(options[index][1]);
            btn3.setText(options[index][2]);
            btn4.setText(options[index][3]);

            if(index == question.length - 1)
            {
                next.setText("SUBMIT");
            }

        }

        //clear the selection
        bg.clearSelection();

    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(geo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(geo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(geo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(geo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new geo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn1;
    private javax.swing.JRadioButton btn2;
    private javax.swing.JRadioButton btn3;
    private javax.swing.JRadioButton btn4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton next;
    private javax.swing.JLabel ques;
    // End of variables declaration//GEN-END:variables
}
