package quizapp;
import java.awt.*;
import javax.swing.*;

public class it extends javax.swing.JFrame {

String[] question = {
"Q1.  What stands for ICT?",
"Q2.  Who is the father of modern Computer?",    
"Q3.  The name of first computer designed by Charlse Babbage ...",
"Q4.  ENIAC stands for .............",
"Q5.  A byte consists of how many bits?",
"Q6.  Bit stands for ......",
"Q7.  Which is an example for a operating system?",
"Q8.  Which is an example for a web browser?",
"Q9.  Which of these is a free operating system?",
"Q10.  Which is an example for a search engine?",
"Q11.  In how many generations computers are classified?",
"Q12.  The main electronic component in 1st generation is ...",
"Q13.  The period of first generation computers was .....",
"Q14.  An example for first generation computers was ....",
"Q15.  The main electronic component in 2nd generation is ...",
"Q16.  The period of second generation computers was ....",
"Q17.  An example for second Generation Computers was ....",
"Q18.  The main electronic component in 3rd generation is ...",
"Q19.  The main electronic component in 4th generation is ...",
"Q20.  The main electronic component in 5th generation is ...",
"Q21.  What is Universal Serial Bus?",
"Q22.  Why would you use a USB flash drive? For, ....",
"Q23.  The keyboard is an ...... device",
"Q24.  The part of the computer that can physically touch?",
"Q25.  1 GB is equal to, ...."
};

//third item is the correct answer
String[][] options = {
/*1*/{"Inter connected Terminals","International Communication Technology","Information and Communication Technology","International Connected Technology"},
/*2*/{"Blaise Pascal","Lady Ada Augusta","Charles Babbage","John Von Neuman"},
/*3*/{"ENIAC","Difference Engine","Analytical Engine","UNIVAC"},
/*4*/{"Electronic Numerical Integrator Automatic Computer","Electronic Numerical Integrator Automatic Calculator","Electronic Numerical Integrator And Computer","Electronic Numerical Integrator And Calculator"},
/*5*/{"16 bits","2 bits","8 bits","4 bits"},
/*6*/{"Binary Information term","Binary tree","Binary Digit","None"},
/*7*/{"Fire fox","Notepad","Windows 10","Avira"},
/*8*/{"Yahoo","Bing","Chrome","Google"},
/*9*/{"Mac OS","Windows XP","Ubuntu","Windows 7"},
/*10*/{"Opera","Safari","Bing","Vivaldi"},
/*11*/{"2 generations","4 generations","5 generations","3 generations"},
/*12*/{"Transistor","Integrated Circuit","Vacuum Tube","Optical Fibre"},
/*13*/{"1930-1938","1935-1942","1940-1956","1940-1950"},
/*14*/{"IBM 7094","UNIVAC","ENIAC","PDP-11"},
/*15*/{"Vacuum Tube","Integrated Circuit","Transistor","Optical Fibre"},
/*16*/{"1930-1938","1940-1952","1956-1963","1946-1959"},
/*17*/{"EDVAC","IBM 370","IBM 7094","ENIAC"},
/*18*/{"Transistor","Artificial Intelligence","Integrated Circuit","Vacuum Tube"},
/*19*/{"Vacuum Tube","Transistor","Microprocessor","Artificial Intelligence"},
/*20*/{"Transistor","Vacuum Tube","Artificial Intelligence","Microprocessor"},
/*21*/{"SATA port","HDMI Port","USB Port","None of the above"},
/*22*/{"Saving files","Listening music","Backup files","Creating music"},
/*23*/{"Output","Storage","Input","None of the above"},
/*24*/{"Programs","Operating System","Hardware","Software"},
/*25*/{"512 MB","1028 MB","1024 MB","256 MB"}
    
    
};    

    int index = 0, correct = 0;
    ButtonGroup bg = new ButtonGroup();
    
    public it() {
        initComponents();
        
        ImageIcon imagebg2 = new ImageIcon(new ImageIcon("5.png").getImage().getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(), Image.SCALE_DEFAULT));
         jLabel2.setIcon(imagebg2);
        
        bg.add(btn1);
        bg.add(btn2);
        bg.add(btn3);
        bg.add(btn4);
        
        nextActionPerformed(null);
                
       

    }

    public void getSelectedOption(JRadioButton bbtn){
        //to get selected value from the radio button
        //increament the index
        //display radio buttons
        //check if the user selected the correct ans
        
        System.out.println(bbtn.getText());
        System.out.println(options[index][2]);
                
        if(bbtn.getText().equals(options[index][2]))
        {
            correct++;
        }
        
        index++;
        enableradiobtns(false);
    }
    
    //enable/ disable radiobuttons
    public void enableradiobtns(boolean yesno){
        btn1.setEnabled(yesno);
        btn2.setEnabled(yesno);
        btn3.setEnabled(yesno);
        btn4.setEnabled(yesno);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn1 = new javax.swing.JRadioButton();
        next = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ques = new javax.swing.JLabel();
        btn2 = new javax.swing.JRadioButton();
        btn3 = new javax.swing.JRadioButton();
        btn4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quizz Time - Information Technology");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn1.setBackground(new java.awt.Color(204, 204, 204));
        btn1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn1.setText("btn1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 330, 30));

        next.setBackground(new java.awt.Color(51, 51, 51));
        next.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("NEXT");
        next.setToolTipText("Choose An Answer And Click Here To Go To Next Quiz");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 420, 110, 34));

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("BACK");
        jButton6.setToolTipText("Click Here To Go To Quiz Time Dashboard");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 110, 34));

        jPanel2.setBackground(new java.awt.Color(120, 59, 241));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quizz Time - Information Technology");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 70));

        ques.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ques.setText("ques");
        jPanel1.add(ques, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 550, 140));

        btn2.setBackground(new java.awt.Color(204, 204, 204));
        btn2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn2.setText("btn2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 330, 30));

        btn3.setBackground(new java.awt.Color(204, 204, 204));
        btn3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn3.setText("btn3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 330, 30));

        btn4.setBackground(new java.awt.Color(204, 204, 204));
        btn4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn4.setText("btn4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 330, 30));

        jLabel2.setText("jLabel1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 300, 290));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        setVisible(false);
        f2 back = new f2();
        back.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        
       if(next.getText().equals("RESTART"))
        {
            //restart the quiz
            next.setText("NEXT");
            jPanel1.setBackground(Color.WHITE);
            index = 0;
            correct = 0;
        }
        
        if(index == question.length)
        {
            //display the user score
            //ques.setText("Your Score: " + correct + " / " + question.length);
            
            if(correct >= 15)
            {
                JOptionPane optpanel = new JOptionPane();
                
                optpanel.setBackground(Color.GREEN);
                optpanel.showMessageDialog(null,"Congratulations!  Your Score is : " + correct + " / " + question.length,
                "Quiz Finished", optpanel.PLAIN_MESSAGE);
                
                //System.exit(0);
            }
               
            
            else{
                JOptionPane optpanel2 = new JOptionPane();
                optpanel2.setBackground(Color.RED);
                
                optpanel2.showMessageDialog(null,"Sorry!  Your Score is : " + correct + " / " + question.length,
                "Quiz Finished", optpanel2.PLAIN_MESSAGE);
                
                
                ques.setText("");
                btn1.setText("");
                btn2.setText("");
                btn3.setText("");
                btn4.setText("");
            }
            
            next.setText("RESTART");
        }
        
        else
        {
            //enable radio btns
                 enableradiobtns(true);

                 //display next question
                 ques.setText(question[index]);

                 btn1.setText(options[index][0]);
                 btn2.setText(options[index][1]);
                 btn3.setText(options[index][2]);
                 btn4.setText(options[index][3]);
                 
                 
                 if(index == question.length - 1)
                 {
                     next.setText("SUBMIT");
                 }
                 
        }
        
        //clear the selection
        bg.clearSelection();
        
        
        
    }//GEN-LAST:event_nextActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        //increament to go to next question
        getSelectedOption(btn1);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        getSelectedOption(btn2);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        getSelectedOption(btn3);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        getSelectedOption(btn4);
    }//GEN-LAST:event_btn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(it.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(it.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(it.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(it.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new it().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn1;
    private javax.swing.JRadioButton btn2;
    private javax.swing.JRadioButton btn3;
    private javax.swing.JRadioButton btn4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton next;
    private javax.swing.JLabel ques;
    // End of variables declaration//GEN-END:variables
}
