package quizapp;
import java.awt.*;
import javax.swing.*;

import javax.swing.ButtonGroup;

public class media extends javax.swing.JFrame {

String[] question = {
    "Q1.  Who is The Father of Television?",
    "Q2.  Which year introduced electronic television to world",
    "Q3.  The year introduced 1st Television network in Sri Lanka",
    "Q4.  Which is the first TV channel in Sri Lanka?",
    "Q5.  Which is the first private TV channel in Sri Lanka?",
    "Q6.  Which is the first tamil TV channel in Sri Lanka?",
    "Q7.  Who invented the printing machine?",
    "Q8.  Which is the first sinhala newspaper in Sri Lanka?",
    "Q9.  What is the first magazine in Sri Lanka?",
    "Q10.  Who is The Father of Radio?",
    "Q11.  Who is The Father of Telephone?",
    "Q12.  In which year introduced cinema in the world?",
    "Q13.  In which year introduced cinema in Sri Lanka?",
    "Q14.  What is the first sinhala film in Sri Lanka?",
    "Q15.  What is the first color film in Sri Lanka?",
    "Q16.  Introduced Cellular telephone services Sri Lanka in?",
    "Q17.  Who is the Father of the Internet?",
    "Q18.  What is the first news website in Sri Lanka?",
    "Q19.  What was the first social media platform?",
    "Q20.  Who is the Founder of Facebook?",
    "Q21.  Who is the Founder of WhatsApp?",
    "Q22.  Who is the Founder of Telegram?",
    "Q23.  Who is the Founder of Instagram?",
    "Q24.  What is the most popular social media platform in 2023?",
    "Q25.  The average time person spend on social media per day?"
    };
    
//first item is the correct answer
String[][] options = {
/*1*/ {"John Logie Baird","Philo Farnsworth","Kenjiro Takayanagi","Charles Francis Jenkins"},
/*2*/ {"1927","1920","1912","1928"},
/*3*/ {"1979","1980","1978","1981"},
/*4*/ {"The Independent Television Network (ITN)","Sirasa TV","TV Derana","Rupavahini"},
/*5*/ {"TNL TV","Sirasa TV","TV Derana","Siyatha TV"},
/*6*/ {"Shakthi TV","Vasantham TV","Nethra TV","Channel Eye"},
/*7*/ {"Johannes Gutenberg","Peter Abelard","Macro Polo","None of the above"},
/*8*/ {"Lakmini Pahana","Dinamina","Lankadeepa","Silumina"},
/*9*/ {"The Ceylon Times","Hi!! Magazine","Siriththiran","EDEX magazine"},
/*10*/ {"Guglielmo Marconi","Nikola Tesla","Reginald Fessenden","William Dubilier"},
/*11*/ {"Alexander Graham Bell","Antonio Meucci","Johann Philipp Reis","Amos Dolbear"},
/*12*/ {"1895","1880","1872","1890"},
/*13*/ {"1901","1912","1932","1948"},
/*14*/ {"Kadawunu Poronduwa","Thun Man Handiya","Golu Hadawatha","Nidhanaya"},
/*15*/ {"Ranmuthu Duwa","Rekava","Parasathu Mal","Sath Samudura"},
/*16*/ {"1989","1980","1972","1990"},
/*17*/ {"Vint Cerf","Tim Berners‑Lee","Bill Gates","Mark Zuckerberg"},
/*18*/ {"newsfirst.lk","adaderana.lk","newswire.lk","dailymirror.lk"},
/*19*/ {"Six Degrees","MySpace","Friendster","Facebook"},
/*20*/ {"Mark Zuckerberg","Mike Krieger","Pavel Durov","Jan Koum"},
/*21*/ {"Jan Koum","Mark Zuckerberg","Mike Krieger","Pavel Durov"},
/*22*/ {"Pavel Durov","Mike Krieger","Mark Zuckerberg","Jan Koum"},
/*23*/ {"Mike Krieger","Mark Zuckerberg","Jan Koum","Pavel Durov"},
/*24*/ {"Facebook ","Instagram","Twitter","WhatsApp"},
/*25*/ {"2 hours and 24 minutes","2 hours","1 hour and 24 minutes","3 hours"}

};

    int index = 0, correct = 0;
    ButtonGroup bg = new ButtonGroup();
    
    public media() {
        initComponents();
        
        ImageIcon imagebg = new ImageIcon(new ImageIcon("p4.png").getImage().getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(), Image.SCALE_DEFAULT));
         jLabel2.setIcon(imagebg);
        
        bg.add(btn5);
        bg.add(btn6);
        bg.add(btn7);
        bg.add(btn8);
        
        nextActionPerformed(null);
    }
    
    public void getSelectedOption(JRadioButton bbtn){
        //to get selected value from the radio button
        //increament the index
        //display radio buttons
        //check if the user selected the correct ans
        
        System.out.println(bbtn.getText());
        System.out.println(options[index][0]);
                
        if(bbtn.getText().equals(options[index][0]))
        {
            correct++;
        }
        
        index++;
        enableradiobtns(false);
    }
    
    //enable/ disable radiobuttons
    public void enableradiobtns(boolean yesno){
        btn5.setEnabled(yesno);
        btn6.setEnabled(yesno);
        btn7.setEnabled(yesno);
        btn8.setEnabled(yesno);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn5 = new javax.swing.JRadioButton();
        btn6 = new javax.swing.JRadioButton();
        btn7 = new javax.swing.JRadioButton();
        btn8 = new javax.swing.JRadioButton();
        ques = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(120, 59, 241));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quizz Time - Communication (Media)");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 70));

        jLabel2.setText("jLabel1");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 180, 170));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(120, 59, 241));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tekton Pro Ext", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quizz Time - General Knowledge");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 70));

        btn5.setBackground(new java.awt.Color(204, 204, 204));
        btn5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn5.setText("btn1");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel1.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 330, 30));

        btn6.setBackground(new java.awt.Color(204, 204, 204));
        btn6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn6.setText("btn2");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 330, 30));

        btn7.setBackground(new java.awt.Color(204, 204, 204));
        btn7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn7.setText("btn3");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel1.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 330, 30));

        btn8.setBackground(new java.awt.Color(204, 204, 204));
        btn8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn8.setText("btn4");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel1.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 330, 30));

        ques.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        ques.setText("ques");
        jPanel1.add(ques, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 550, 140));

        back.setBackground(new java.awt.Color(51, 51, 51));
        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.setToolTipText("Click Here To Go To Quiz Time Dashboard");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 110, 34));

        next.setBackground(new java.awt.Color(51, 51, 51));
        next.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        next.setForeground(new java.awt.Color(255, 255, 255));
        next.setText("NEXT");
        next.setToolTipText("Choose An Answer And Click Here To Go To Next Quiz");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 420, 110, 34));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        //increament to go to next question
        getSelectedOption(btn5);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        getSelectedOption(btn6);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        getSelectedOption(btn7);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        getSelectedOption(btn8);
    }//GEN-LAST:event_btn8ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        setVisible(false);
        f2 back = new f2();
        back.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed

        if(next.getText().equals("RESTART"))
        {
            //restart the quiz
            next.setText("NEXT");
            jPanel1.setBackground(Color.WHITE);
            index = 0;
            correct = 0;
        }

        if(index == question.length)
        {
            //display the user score
            //ques.setText("Your Score: " + correct + " / " + question.length);

            if(correct >= 15)
            {
                JOptionPane optpanel = new JOptionPane();

                optpanel.setBackground(Color.GREEN);
                optpanel.showMessageDialog(null,"Congratulations!  Your Score is : " + correct + " / " + question.length,
                    "Quiz Finished", optpanel.PLAIN_MESSAGE);

                //System.exit(0);
            }

            else{
                JOptionPane optpanel2 = new JOptionPane();
                optpanel2.setBackground(Color.RED);

                optpanel2.showMessageDialog(null,"Sorry!  Your Score is : " + correct + " / " + question.length,
                    "Quiz Finished", optpanel2.PLAIN_MESSAGE);

                ques.setText("");
                btn5.setText("");
                btn6.setText("");
                btn7.setText("");
                btn8.setText("");
            }

            next.setText("RESTART");
        }

        else
        {
            //enable radio btns
            enableradiobtns(true);

            //display next question
            ques.setText(question[index]);

            btn5.setText(options[index][0]);
            btn6.setText(options[index][1]);
            btn7.setText(options[index][2]);
            btn8.setText(options[index][3]);

            if(index == question.length - 1)
            {
                next.setText("SUBMIT");
            }

        }

        //clear the selection
        bg.clearSelection();
    }//GEN-LAST:event_nextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(media.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(media.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(media.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(media.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new media().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JRadioButton btn5;
    private javax.swing.JRadioButton btn6;
    private javax.swing.JRadioButton btn7;
    private javax.swing.JRadioButton btn8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton next;
    private javax.swing.JLabel ques;
    // End of variables declaration//GEN-END:variables
}
